version: '3.7'

services:
  db5:
      image: mysql:5.7.30 
      container_name: mysql
        #ports:
        # - "3306:3306"
        #restart: always
      volumes:
        - dbmysql:/var/lib/mysql
        - ./sql-script:/docker-entrypoint-initdb.d #adding empty database
        - ./conf/my.cnf:/etc/mysql/my.cnf
      environment:
        - MYSQL_ROOT_PASSWORD=supersecret
      env_file:
        - ./.db.env
  app:
      image: quay.io/ingimar/shiny:latest
        #image: nrm-shiny:v3
      container_name: bulk
      ports:
        - "8080:8080"
volumes:
  dbmysql:
